[window]
padding.x=10
padding.y=20
[env]
TERM = "xterm-256color"
[font]
size = 14.0
builtin_box_drawing = true
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"
